### ISSUE TITLE
demo page numbers

### ISSUE THREAD

**Issue by davidjnz** [ali1234/raspi-teletext#12]
Is it possible to specify the demo page number.  Currently the demo page is 100 and 101 but i would like to set it to be 500 and 501?

**Comment by Tachiorz** [comment]
You have to broadcast one of the packets: 8/30/0, 8/30/1, 8/30/2 or 8/30/3 to specify initial page. And change `demo_buffer.h`

**Comment by ali1234** [comment]
I wanted to avoid putting any encoding logic into this software, so you will need to manually change the hardcoded arrays and recompile. Encoding and decoding belongs in a separate library which I am still working on.

**Comment by ali1234** [comment]
Going to close this as the demo is just that - not meant for production use, just to ensure it is working. You should pipe in your own packets from an external program if you need something different.
