### ISSUE TITLE
Please add a section to the documentation about setting sdtv=2 in config.txt for PAL

### ISSUE THREAD

**Issue by laust** [ali1234/raspi-teletext#27]
It would be nice to have a section in the documentation that explains (or reminds you) that it is necessary to set 
sdtv=2
in the config.txt file if you need to run teletext on a PAL television. 

If this is not done and then the tvctl on command will give you start CEA604 mode instead of Teletext.

**Comment by ali1234** [comment]
Fixed in a21301aff14a33319a4cf686930aee5d1fc2fc38

**Comment by laust** [comment]
Perfect, thank you. And thank you for a great project.
